name: GraalVM Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      max-parallel: 1

    if: github.ref == 'refs/heads/master'
    steps:
      - name: Setup GraalVM action
        # You may pin to the exact commit or the version.
        # uses: ayltai/setup-graalvm@eb0db9af1ceb6dadb398847c7e23fc3afa09c0d3
        uses: ayltai/setup-graalvm@master
        with:
          # The JDK version to be installed with GraalVM. E.g. 8, 11. See https://github.com/graalvm/graalvm-ce-builds/releases
          java-version: 11 # optional
          # The version of GraalVM to make available on PATH. E.g. 20.1.0, 19.3.2. See https://github.com/graalvm/graalvm-ce-builds/releases
          # Allineare la versione con pom.xml
          graalvm-version: 21.1.0
          # Install GraalVM Native Image
          native-image: true # optional

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      - name: Windows msvc setup
        uses: ilammy/msvc-dev-cmd@v1.9.0
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Windows msbuild setup
        uses: microsoft/setup-msbuild@v1
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Call maven
        run: mvn --no-transfer-progress -B package --file pom.xml -DskipNativeVersion=false

#      - name: Commit files
#        if: ${{ matrix.os == 'windows-latest' }}
#        run: |
#          dir D:\a\FantaSoccerAsta\FantaSoccerAsta\target\
#          copy D:\a\FantaSoccerAsta\FantaSoccerAsta\target\FantaSoccerAsta.exe   D:\a\FantaSoccerAsta\FantaSoccerAsta\executable\windows
#          #copy D:\a\FantaSoccerAsta\FantaSoccerAsta\target\FantaSoccerAsta-*.exe D:\a\FantaSoccerAsta\FantaSoccerAsta\executable\windows
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add *.exe
#          git commit -m "[Automated] Added Windows build files"
#          git pull

      - name: Commit files
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          dir D:\a\FantaSoccerAsta\FantaSoccerAsta\target\
          copy D:\a\FantaSoccerAsta\FantaSoccerAsta\target\FantaSoccerAsta.exe   D:\a\FantaSoccerAsta\FantaSoccerAsta\executable\windows
          #copy D:\a\FantaSoccerAsta\FantaSoccerAsta\target\FantaSoccerAsta-*.exe D:\a\FantaSoccerAsta\FantaSoccerAsta\executable\windows
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.exe
          git commit -m "[Automated] Added Windows build files"
          git pull

      - name: Read release.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(date "+%Y%m%d-%H%M%S")
          echo "::set-output name=RELEASE_BODY::$r"

      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: D:\a\FantaSoccerAsta\FantaSoccerAsta\target\FantaSoccerAsta.exe
          asset_name: Eseguibile Windows
          body: |
            Rilascio del ${{ steps.read_release.outputs.RELEASE_BODY }}

#      - name: Commit files
#        if: ${{ matrix.os == 'ubuntu-latest' }}
#        run: |
#          cp /home/runner/work/FantaSoccerAsta/FantaSoccerAsta/target/FantaSoccerAsta /home/runner/work/FantaSoccerAsta/FantaSoccerAsta/executable/linux/
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add .
#          git commit -m "[Automated] Added Linux build files"
#          git pull

#      - name: Commit files
#        if: ${{ matrix.os == 'macos-latest' }}
#        run: |
#          cp /Users/runner/work/FantaSoccerAsta/FantaSoccerAsta/target/FantaSoccerAsta /Users/runner/work/FantaSoccerAsta/FantaSoccerAsta/executable/mac/
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add .
#          git commit -m "[Automated] Added Mac build files"
#          git pull

#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
