name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Build with Maven
      run: mvn --no-transfer-progress -B package --file pom.xml
