name: Meterian vulnerability scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.15
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                cli_args: "" #--autofix" #[ Meterian CLI Options ]
                
#          - name: Push changes
#            uses: ad-m/github-push-action@master
#            with:
#                github_token: ${{ secrets.GITHUB_TOKEN }}
#                branch: ${{ github.ref }}                
